# Generated by Django 2.1.7 on 2019-11-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselist',
            name='CaseMail',
            field=models.EmailField(max_length=30),
        ),
    ]
