# Generated by Django 2.1.7 on 2019-11-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20191116_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountName', models.CharField(max_length=30)),
                ('AccountLocation', models.CharField(max_length=30)),
                ('AccountPhone', models.CharField(max_length=10)),
                ('AccountMail', models.CharField(max_length=30)),
                ('AccountPassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BookingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingPhone', models.CharField(max_length=10)),
                ('BookingName', models.CharField(max_length=30)),
                ('BookingLocation', models.CharField(max_length=30)),
                ('BookingDate', models.CharField(max_length=30)),
                ('BookingRemark', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='CaseList',
        ),
    ]
