# Generated by Django 2.1.7 on 2019-11-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20191116_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglist',
            name='BookingQuantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
